# Tflint workflow checks for possible errors, and best practices in your terraform code
name: tf-lint-and-security-scan
on:
    workflow_call:
        inputs:
            working_directory:
                description: 'Directory where main.tf exist of the module.'
                required: false
                type: string
                default: './examples/'
        secrets:
            GITHUB_PAT:
                required: true
                description: 'PAT of the service-account to run the jobs.'

jobs:
    terraform-linting:
        name: Terrafrom Linting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Checkout source code

            - uses: terraform-linters/setup-tflint@v4
              name: Setup TFLint
              with:
                tflint_version: v0.44.1
                github_token: ${{ secrets.GITHUB_PAT }}

            - name: Show version
              run: tflint --version

            - name: Init TFLint
              run: tflint --init
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Run TFLint
              run: tflint --recursive --color --force -f compact
              env:
                GITHUB_TOKEN: ${{ github.token }}

    terraform-security:
      name: Terraform Security Scan
      needs: terraform-linting
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
          name: Checkout source code
  
        - name: Setup tfsec
          uses: aquasecurity/tfsec-sarif-action@v0.1.4
          with:
            sarif_file: tfsec.sarif
            working_directory: ${{ inputs.working_directory}}
            full_repo_scan: true
  
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: tfsec.sarif
          continue-on-error: true
  
        - name: tfsec commenter for PR
          uses: tfsec/tfsec-pr-commenter-action@v1.3.1
          with:
            github_token: ${{ secrets.GITHUB_PAT }}
            working_directory: ${{ inputs.working_directory}}
  
        - name: Terraform security scan Advanced
          uses: triat/terraform-security-scan@v3.2.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
            tfsec_actions_comment: true
            tfsec_output_format: sarif
          continue-on-error: true